global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: [
        'kafka-1:7071',
        'kafka-2:7071',
        'kafka-3:7071'
      ]
  - job_name: 'zookeeper'
    static_configs:
      - targets: [ 'zookeeper-jmx-exporter:7071' ]