global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: [
        'kafka-1:7071',
        'kafka-2:7071',
        'kafka-3:7071'
      ]
  - job_name: 'zookeeper'
    metrics_path: '/metrics'
    static_configs:
      - targets: [
        'zookeeper-1:7070',
        'zookeeper-2:7070',
        'zookeeper-3:7070'
      ]