{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": {
     "query": "label_values(kafka_cluster_partition_replicascount, topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Kafka Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Controller",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globalpartitioncount)",
     "legendFormat": "leaders"
    },
    {
     "expr": "sum(kafka_cluster_partition_replicascount)",
     "legendFormat": "replicas"
    }
   ]
  },
  {
   "title": "Topics at Min ISR",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_atminisr)",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Under-Replicated and Offline Partitions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount)",
     "legendFormat": "offline"
    },
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions)",
     "legendFormat": "under-replicated"
    }
   ]
  },
  {
   "title": "Network Thread Pool Busyness",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - kafka_network_socketserver_networkprocessoravgidlepercent",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(sum by (instance)(delta(kafka_network_requestmetrics_requests_total[1m])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errors Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(error)(delta(kafka_network_requestmetrics_errors_total{error!=\"NONE\",error!=\"CONCURRENT_TRANSACTIONS\"}[1m]))",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "messages" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(delta(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=~\"[[topic]]\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(delta(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=~\"[[topic]]\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "Bps", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(delta(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic=~\"[[topic]]\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "ZooKeeper Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Quorum Leader",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(replicaId)(zookeeper_leader)",
     "legendFormat": "Node {{replicaId}}"
    }
   ]
  },
  {
   "title": "Reported Quorum Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(zookeeper_quorumsize) / 3", "legendFormat": "Reported Quorum Size" }
   ]
  },
  {
   "title": "Tree Size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(zookeeper_nodecount)", "legendFormat": "nodes" },
    { "expr": "max(zookeeper_watchcount)", "legendFormat": "watches" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(zookeeper_numaliveconnections)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(zookeeper_outstandingrequests)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max by (instance)(zookeeper_avgrequestlatency)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}