version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    healthcheck:
      test: nc -z localhost 2181 || exit -1
    ports:
      - "2181:2181"
      - "1099:1099"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      JMXPORT: 1099

  zookeeper-jmx-exporter:
    image: sscaling/jmx-prometheus-exporter:latest
    depends_on:
      - zookeeper
    ports:
      - "7071:7071"
    environment:
      SERVICE_PORT: 7071
    volumes:
      - ./zookeeper/zookeeper-jmx-exporter-config.yml:/opt/jmx_exporter/config.yml

  kafka-1:
    image: kafka_with_jmx_exporter:latest
    build: ./kafka
    depends_on:
      - zookeeper
    ports:
      - "19092:19092"
      - "17071:7071"
      - "11099:1099"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      EXTRA_ARGS: -javaagent:/opt/kafka/libs/jmx_prometheus_javaagent.jar=7071:/opt/kafka/libs/jmx.yml
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-1:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENERS: INSIDE://kafka-1:9092,OUTSIDE://kafka-1:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      JMX_PORT: 1099
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka-2:
    image: kafka_with_jmx_exporter:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "27071:7071"
      - "21099:1099"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      EXTRA_ARGS: -javaagent:/opt/kafka/libs/jmx_prometheus_javaagent.jar=7071:/opt/kafka/libs/jmx.yml
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-2:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENERS: INSIDE://kafka-2:9092,OUTSIDE://kafka-2:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      JMX_PORT: 1099
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka-3:
    image: kafka_with_jmx_exporter:latest
    depends_on:
      - zookeeper
    ports:
      - "39092:39092"
      - "37071:7071"
      - "31099:1099"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      EXTRA_ARGS: -javaagent:/opt/kafka/libs/jmx_prometheus_javaagent.jar=7071:/opt/kafka/libs/jmx.yml
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-3:9092,OUTSIDE://localhost:39092
      KAFKA_LISTENERS: INSIDE://kafka-3:9092,OUTSIDE://kafka-3:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      JMX_PORT: 1099
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    user: root
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"